"""Start robot_state_publisher from a URDF rendered by render_robot_urdf.launch.py."""

from pathlib import Path

from launch import LaunchContext
from launch import LaunchDescription
from launch import LaunchDescriptionEntity
from launch.actions import DeclareLaunchArgument
from launch.actions import OpaqueFunction
from launch.actions import SetLaunchConfiguration
from launch.substitutions import LaunchConfiguration
from launch.utilities.type_utils import normalize_typed_substitution
from launch.utilities.type_utils import perform_typed_substitution
from launch_ros.actions import Node
from launch_ros.descriptions import ParameterFile
from launch_ros.descriptions import ParameterValue
import ros2_launch_helpers as rlh


def generate_launch_description() -> LaunchDescription:
    """Declare the URDF, parameter, namespace, and node-argument inputs for RSP."""
    return LaunchDescription(
        [
            DeclareLaunchArgument('namespace', default_value='', description='Project namespace'),
            DeclareLaunchArgument('robot_name', description='The unique name for the robot'),
            DeclareLaunchArgument(
                'robot_urdf_file', description='Path to the rendered robot URDF file.'
            ),
            DeclareLaunchArgument(
                'robot_rsp_params_file',
                description='Path to the complete robot parameter YAML file.',
            ),
            DeclareLaunchArgument(
                'robot_rsp_params_file_allow_substs',
                choices=['True', 'true', 'False', 'false'],
                description='Allow ROS launch substitutions in robot_rsp_params_file',
            ),
            DeclareLaunchArgument(
                'use_sim_time',
                choices=['True', 'true', 'False', 'false'],
                description='Use ROS time from /clock if true.',
            ),
            DeclareLaunchArgument(
                'node_args',
                default_value='{"output":"both","ros_arguments":["--log-level","info"]}',
                description=rlh.LAUNCH_ACTION_ARGUMENTS_DESC,
            ),
            rlh.RequireFile(path=LaunchConfiguration('robot_rsp_params_file')),
            rlh.RequireFile(path=LaunchConfiguration('robot_urdf_file')),
            # Insert `robot_type`, `robot_namespace` and `robot_prefix` into the launch context.
            # Their values can then be substituted in the parameter file if needed.
            SetLaunchConfiguration('robot_type', 'rbvogui'),
            rlh.SetRobotNamespace(
                namespace=LaunchConfiguration('namespace'),
                robot_name=LaunchConfiguration('robot_name'),
                output_context_key='robot_namespace',
            ),
            rlh.SetRobotPrefix(
                robot_name=LaunchConfiguration('robot_name'), output_context_key='robot_prefix'
            ),
            OpaqueFunction(function=_launch_node),
        ]
    )


def _launch_node(ctx: LaunchContext) -> list[LaunchDescriptionEntity]:
    """Read the completed URDF once and provide its XML as the robot_description parameter."""
    params_allow_substs = perform_typed_substitution(
        ctx,
        normalize_typed_substitution(
            LaunchConfiguration('robot_rsp_params_file_allow_substs'), bool
        ),
        bool,
    )

    robot_urdf_file = LaunchConfiguration('robot_urdf_file').perform(ctx).strip()
    robot_description = Path(robot_urdf_file).read_text(encoding='utf-8')

    actions: list[LaunchDescriptionEntity] = [
        Node(
            package='robot_state_publisher',
            executable='robot_state_publisher',
            namespace=LaunchConfiguration('robot_namespace'),
            parameters=[
                ParameterFile(
                    LaunchConfiguration('robot_rsp_params_file'), allow_substs=params_allow_substs
                ),
                {
                    'robot_description': ParameterValue(robot_description, value_type=str),
                    # RSP republishes this XML on robot_description for consumers that use a topic.
                    'use_robot_description_topic': True,
                    # Link and joint names generated by xacro already include their frame prefixes.
                    'frame_prefix': '',
                    'use_sim_time': ParameterValue(
                        LaunchConfiguration('use_sim_time'), value_type=bool
                    ),
                },
            ],
            **rlh.resolve_node_arguments(
                LaunchConfiguration('node_args').perform(ctx),
                default_arguments={'name': 'robot_state_publisher'},
                extra_rejected_arguments={'namespace'},
            ),
        )
    ]

    return actions
